[package]
name = "brilirs"
version = "0.1.0"
authors = ["Wil Thomason <wil.thomason@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap         = "~2.31"
log          = "~0.4"
serde        = "~1.0"
serde_derive = "~1.0"
serde_json   = "~1.0"
simplelog    = "~0.7"
twox-hash    = "~1.5.0"
