[package]
name = "native"
version = "0.1.0"
authors = ["kavoor <kev29@cornell.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
