[envs.interp_exprs]
command = "cat {filename} | racket src/interp.rkt"
output.exprs_out = "-"

[envs.interp_bril]
command = "./bin/bracket {filename} | brili"
output.bril_out = "-"

[envs.bril]
command = "./bin/bracket {filename} | bril2txt"
output.bril = "-"

